### ISSUE TITLE
v0.1.3 Roadmap

### ISSUE THREAD

**Issue by dfreeman06** [jupyrdf/graph-lsp#5]
* [ ] udpate @jupyterlab/builder so it generates the third-party-licenses.jsonfile
* [ ] include the LICENSE for the bundle servers if possible
* [ ] make some entry_points to start the servers independently
* [ ] add some tests for actually running the bundled servers
* [ ] add readme
* [ ]
